travis:
  secure:
    BINSTAR_TOKEN: tFX4VrEMM7jhzvfBsTOekfjrU/J16DB6IOEGHIpOa/cbBBRihcPHmx4CoYg116ARWH89oXe3Hp+kXmTxioQzhdPQIGT2lLo5JHSXwYgzMZ++Ky/w09QdBBV3L09+MW5NSxgzAfrGU8wzYYsnck2LH3QOhbEGRuP4xg26J26phBnZmT/4XilMh7nNZfpIdi5/LXzgJRiTiWxcbxSUHVYTDgC3pwSY51lk8xLGs4FeAzHwXScZL5n9jVOpT33rRBzgUv5Ak7uNp2UyWBDJvfOx6pnYodNtWFAVER50AGnYVNAbWyp5PO08ewWbjhwdDNd8v6Uq+CM4KwvDGO8DcSpJmI5+wrkSPSV9q3Z2E4oV+DoRRkuiG/uwUG9e3HDN/wSWLRgR7/VCJ2YGLIsU3tg00L+Zz54vK0X6cXK6/BAn9j15BkcdR74cBDlxXmipqNkGk8Cf6fNyR7jeLIKO5HRJSBiB/7Rs44MWgPm1wRmxX++H6DqiHK3fC6OCfHQQea9eS52J3zagsyjViK9Nb1xzQaKPSATcMDNLv0wzuOFyq84pU30ChgnAYkAibk7ZFCDhHM1bqo9099f6+2NkxzvuQZqwNuC0HdCrbG2QCGmZlG0S2Kx/MhYfwTyVINsXeHR5cgf871m/0rALCfOhWk3jfPA+T5x6f48mEUAbjiPBwTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
